#
# linux/drivers/chips/Makefile
#

obj-$(CONFIG_MTD)		+= chipreg.lib
obj-$(CONFIG_MTD_CFI)		+= cfi_probe.lib
obj-$(CONFIG_MTD_CFI_UTIL)	+= cfi_util.lib
obj-$(CONFIG_MTD_CFI_STAA)	+= cfi_cmdset_0020.lib
obj-$(CONFIG_MTD_CFI_AMDSTD)	+= cfi_cmdset_0002.lib
obj-$(CONFIG_MTD_CFI_INTELEXT)	+= cfi_cmdset_0001.lib
obj-$(CONFIG_MTD_GEN_PROBE)	+= gen_probe.lib
obj-$(CONFIG_MTD_JEDECPROBE)	+= jedec_probe.lib
obj-$(CONFIG_MTD_RAM)		+= map_ram.lib
obj-$(CONFIG_MTD_ROM)		+= map_rom.lib
obj-$(CONFIG_MTD_ABSENT)	+= map_absent.lib
obj-$(CONFIG_RTL8676_SPI_FLASH)	+= spi_probe.lib spi_cmd.lib spi_flash.lib
