
# Button Core
obj-$(CONFIG_TBS_BUTTON)		+= btn-core.o

# Button Platform Drivers
obj-$(CONFIG_BUTTON_AR7130)		+= btn_ar7130.o
obj-$(CONFIG_BUTTON_AMAZON_SE)		+= btn_amazon_se.o
obj-$(CONFIG_BUTTON_RT3052)		+= btn_rt3052.o
obj-$(CONFIG_BUTTON_VX180)		+= btn_vx180.o
obj-$(CONFIG_BUTTON_RTL8672)		+= btn_rtl8672.o
obj-$(CONFIG_BUTTON_RTL8676)		+= btn_rtl8676.o

