obj-$(CONFIG_MTD_TESTS) += mtd_oobtest.lib
obj-$(CONFIG_MTD_TESTS) += mtd_pagetest.lib
obj-$(CONFIG_MTD_TESTS) += mtd_readtest.lib
obj-$(CONFIG_MTD_TESTS) += mtd_speedtest.lib
obj-$(CONFIG_MTD_TESTS) += mtd_stresstest.lib
obj-$(CONFIG_MTD_TESTS) += mtd_subpagetest.lib
obj-$(CONFIG_MTD_TESTS) += mtd_torturetest.lib
