
# LED Core
obj-$(CONFIG_NEW_LEDS)			+= led-core.lib
obj-$(CONFIG_LEDS_TBS)			+= led-tbscore.lib
obj-$(CONFIG_LEDS_CLASS)		+= led-class.lib
obj-$(CONFIG_LEDS_TRIGGERS)		+= led-triggers.lib

# LED Platform Drivers
obj-$(CONFIG_LEDS_RTL8672)		+= leds-rtl8672.lib
obj-$(CONFIG_LEDS_RTL8676)		+= leds-rtl8676.lib
obj-$(CONFIG_LEDS_ATMEL_PWM)		+= leds-atmel-pwm.lib
obj-$(CONFIG_LEDS_BD2802)		+= leds-bd2802.lib
obj-$(CONFIG_LEDS_LOCOMO)		+= leds-locomo.lib
obj-$(CONFIG_LEDS_MIKROTIK_RB532)	+= leds-rb532.lib
obj-$(CONFIG_LEDS_S3C24XX)		+= leds-s3c24xx.lib
obj-$(CONFIG_LEDS_AMS_DELTA)		+= leds-ams-delta.lib
obj-$(CONFIG_LEDS_NET48XX)		+= leds-net48xx.lib
obj-$(CONFIG_LEDS_WRAP)			+= leds-wrap.lib
obj-$(CONFIG_LEDS_ALIX2)		+= leds-alix2.lib
obj-$(CONFIG_LEDS_H1940)		+= leds-h1940.lib
obj-$(CONFIG_LEDS_COBALT_QUBE)		+= leds-cobalt-qube.lib
obj-$(CONFIG_LEDS_COBALT_RAQ)		+= leds-cobalt-raq.lib
obj-$(CONFIG_LEDS_SUNFIRE)		+= leds-sunfire.lib
obj-$(CONFIG_LEDS_PCA9532)		+= leds-pca9532.lib
obj-$(CONFIG_LEDS_GPIO)			+= leds-gpio.lib
obj-$(CONFIG_LEDS_CLEVO_MAIL)		+= leds-clevo-mail.lib
obj-$(CONFIG_LEDS_HP6XX)		+= leds-hp6xx.lib
obj-$(CONFIG_LEDS_FSG)			+= leds-fsg.lib
obj-$(CONFIG_LEDS_PCA955X)		+= leds-pca955x.lib
obj-$(CONFIG_LEDS_DA903X)		+= leds-da903x.lib
obj-$(CONFIG_LEDS_WM8350)		+= leds-wm8350.lib
obj-$(CONFIG_LEDS_PWM)			+= leds-pwm.lib

# LED SPI Drivers
obj-$(CONFIG_LEDS_DAC124S085)		+= leds-dac124s085.lib

# LED Triggers
obj-$(CONFIG_LEDS_TRIGGER_TIMER)	+= ledtrig-timer.lib
obj-$(CONFIG_LEDS_TRIGGER_IDE_DISK)	+= ledtrig-ide-disk.lib
obj-$(CONFIG_LEDS_TRIGGER_HEARTBEAT)	+= ledtrig-heartbeat.lib
obj-$(CONFIG_LEDS_TRIGGER_BACKLIGHT)	+= ledtrig-backlight.lib
obj-$(CONFIG_LEDS_TRIGGER_GPIO)		+= ledtrig-gpio.lib
obj-$(CONFIG_LEDS_TRIGGER_DEFAULT_ON)	+= ledtrig-default-on.lib
