#create by scb at 2011-8-26
#for manager the stub code
all: 3g-stub

#let the warnning become error
CFLAGS += -Werror -L../3g-mngr/lib

#3g-stub:	3g-stub.c 3g-stub.h
#	$(CC) $(CFLAGS)    -Os -o 3g-stub  3g-stub.c -l3g-util

clean:
	rm -f 3g-stub *.o

	
	
