#
# linux/drivers/maps/Makefile
#

ifeq ($(CONFIG_MTD_COMPLEX_MAPPINGS),y)
obj-$(CONFIG_MTD)		+= map_funcs.lib
endif

# Chip mappings
obj-$(CONFIG_MTD_CDB89712)	+= cdb89712.lib
obj-$(CONFIG_MTD_ARM_INTEGRATOR)+= integrator-flash.lib
obj-$(CONFIG_MTD_CFI_FLAGADM)	+= cfi_flagadm.lib
obj-$(CONFIG_MTD_DC21285)	+= dc21285.lib
obj-$(CONFIG_MTD_DILNETPC)	+= dilnetpc.lib
obj-$(CONFIG_MTD_L440GX)	+= l440gx.lib
obj-$(CONFIG_MTD_AMD76XROM)	+= amd76xrom.lib
obj-$(CONFIG_MTD_ESB2ROM)	+= esb2rom.lib
obj-$(CONFIG_MTD_ICHXROM)	+= ichxrom.lib
obj-$(CONFIG_MTD_CK804XROM)	+= ck804xrom.lib
obj-$(CONFIG_MTD_TSUNAMI)	+= tsunami_flash.lib
obj-$(CONFIG_MTD_PXA2XX)	+= pxa2xx-flash.lib
obj-$(CONFIG_MTD_MBX860)	+= mbx860.lib
obj-$(CONFIG_MTD_CEIVA)		+= ceiva.lib
obj-$(CONFIG_MTD_OCTAGON)	+= octagon-5066.lib
obj-$(CONFIG_MTD_PHYSMAP)	+= physmap.lib
obj-$(CONFIG_MTD_PHYSMAP_OF)	+= physmap_of.lib
obj-$(CONFIG_MTD_PMC_MSP_EVM)   += pmcmsp-flash.lib
obj-$(CONFIG_MTD_PMC_MSP_RAMROOT)+= pmcmsp-ramroot.lib
obj-$(CONFIG_MTD_PCMCIA)	+= pcmciamtd.lib
obj-$(CONFIG_MTD_RPXLITE)	+= rpxlite.lib
obj-$(CONFIG_MTD_TQM8XXL)	+= tqm8xxl.lib
obj-$(CONFIG_MTD_SA1100)	+= sa1100-flash.lib
obj-$(CONFIG_MTD_IPAQ)		+= ipaq-flash.lib
obj-$(CONFIG_MTD_SBC_GXX)	+= sbc_gxx.lib
obj-$(CONFIG_MTD_SC520CDP)	+= sc520cdp.lib
obj-$(CONFIG_MTD_NETSC520)	+= netsc520.lib
obj-$(CONFIG_MTD_TS5500)	+= ts5500_flash.lib
obj-$(CONFIG_MTD_SUN_UFLASH)	+= sun_uflash.lib
obj-$(CONFIG_MTD_VMAX)		+= vmax301.lib
obj-$(CONFIG_MTD_SCx200_DOCFLASH)+= scx200_docflash.lib
obj-$(CONFIG_MTD_DBOX2)		+= dbox2-flash.lib
obj-$(CONFIG_MTD_SOLUTIONENGINE)+= solutionengine.lib
obj-$(CONFIG_MTD_PCI)		+= pci.lib
obj-$(CONFIG_MTD_ALCHEMY)       += alchemy-flash.lib
obj-$(CONFIG_MTD_AUTCPU12)	+= autcpu12-nvram.lib
obj-$(CONFIG_MTD_EDB7312)	+= edb7312.lib
obj-$(CONFIG_MTD_IMPA7)		+= impa7.lib
obj-$(CONFIG_MTD_FORTUNET)	+= fortunet.lib
obj-$(CONFIG_MTD_REDWOOD)	+= redwood.lib
obj-$(CONFIG_MTD_UCLINUX)	+= uclinux.lib
obj-$(CONFIG_MTD_NETtel)	+= nettel.lib
obj-$(CONFIG_MTD_SCB2_FLASH)	+= scb2_flash.lib
obj-$(CONFIG_MTD_H720X)		+= h720x-flash.lib
obj-$(CONFIG_MTD_SBC8240)	+= sbc8240.lib
obj-$(CONFIG_MTD_IXP4XX)	+= ixp4xx.lib
obj-$(CONFIG_MTD_IXP2000)	+= ixp2000.lib
obj-$(CONFIG_MTD_WRSBC8260)	+= wr_sbc82xx_flash.lib
obj-$(CONFIG_MTD_DMV182)	+= dmv182.lib
obj-$(CONFIG_MTD_PLATRAM)	+= plat-ram.lib
obj-$(CONFIG_MTD_OMAP_NOR)	+= omap_nor.lib
obj-$(CONFIG_MTD_INTEL_VR_NOR)	+= intel_vr_nor.lib
obj-$(CONFIG_MTD_BFIN_ASYNC)	+= bfin-async-flash.lib
obj-$(CONFIG_MTD_RBTX4939)	+= rbtx4939-flash.lib
obj-$(CONFIG_MTD_VMU)		+= vmu-flash.lib
obj-$(CONFIG_RTL819X_SPI_FLASH) += rtl819x_flash.lib
obj-$(CONFIG_MTD_RTL8672)	+= rtl8672_flash.lib
obj-$(CONFIG_MTD_RTL8676)	+= rtl8676_flash.lib
