EXTRA_CFLAGS += -DCHIP_RTL8367RB
obj-y += smi.o rtl8367b_asicdrv.o rtl8367b_asicdrv_cputag.o port.o rtl8367b_asicdrv_dot1x.o
obj-y += rtl8367b_asicdrv_mib.o rtl8367b_asicdrv_vlan.o
EXTRA_CFLAGS += -I$(DIR_LINUX)/drivers/net/rtl8367b
