/*
** Copyright (c) 2009 by Silicon Laboratories
**
** $Id: proslic_version.c,v 1.1 2011/03/15 08:13:30 yachang Exp $
**
** proslic_version.c
** ProSLIC API Version
**
** Author(s): 
** cdp
**
** Distributed by: 
** Silicon Laboratories, Inc
**
** This file contains proprietary information.	 
** No dissemination allowed without prior written permission from
** Silicon Laboratories, Inc.
** 
** THIS FILE IS AUTOGENERATED - DO NOT MODIFY
**
*/

char *proslicAPIVersion = "5.0.1";