/*
   This file has been manually derived by
   'src/include/drv_dsl_cpe_api_config.h' which is generated by configure.
   It is intended to be included within kernel build of DSL CPE API.
*/

/* Include ADSL autoboot handling in driver */
#define INCLUDE_ADSL_AUTOBOOT

/* Include ADSL CEOC support */
#define INCLUDE_ADSL_CEOC

/* Include ADSL LED support */
#define INCLUDE_ADSL_LED

/* Include ADSL MIB support */
#define INCLUDE_ADSL_MIB

/* Include ADSL Winhost support for debug purpose only! */
#define INCLUDE_ADSL_WINHOST_DEBUG

/* Add DANUBE support */
#define INCLUDE_DSL_CPE_API_DANUBE

/* Enable debug printouts */
/* #undef INCLUDE_DSL_CPE_API_DEBUG */


/* Package definitions has been renamed to avoid redefinition within kernel */
/* build as follos: */
/*    ORIGINAL_DEFINE  ->  DSL_CPE_API_ORIGINAL_DEFINE */

/* Name of package */
#define DSL_CPE_API_PACKAGE "drv_dsl_cpe_api"

/* Define to the address where bug reports for this package should be sent. */
#define DSL_CPE_API_PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define DSL_CPE_API_PACKAGE_NAME "DSL CPE API driver"

/* Define to the full name and version of this package. */
#define DSL_CPE_API_PACKAGE_STRING "DSL CPE API driver 1.0.3"

/* Define to the one symbol short name of this package. */
#define DSL_CPE_API_PACKAGE_TARNAME "drv_dsl_cpe_api"

/* Define to the version of this package. */
#define DSL_CPE_API_PACKAGE_VERSION "1.0.3"

/* Version number of package */
#define DSL_CPE_API_VERSION "1.0.3"
