# Auto-generated by EclipseNSIS Script Wizard

# Version number in format: maj.min.build (e.g. 1.0.3)
!define VERSION_DRV 3.2.3
!define VERSION_CTRL 3.2.3

# Patch version identifier if needed (e.g. a) or empty
!define PATCH_DRV
!define PATCH_CTRL

!define DEVICE_LONG "DANUBE"
!define DEVICE_FILE "danube"

!include "setup.nsi"

