
#***********************************************************************
#*                                                                     *
#*   MODULE:  Serial Driver Interface Makefile                         * 
#*                                                                     *
#*---------------------------------------------------------------------*

obj-y   := uart2c.o uartclock.o uartTransmit.o uartTest.o
