
install:
	@echo "Installing /usr/rtl8192su"
	@-mkdir -p ${FSROOT}/usr/rtl8192su/
	@cp -Lrf rtl8192su/*.* ${FSROOT}/usr/rtl8192su/
	@chmod -R +w ${FSROOT}/usr/rtl8192su/*

clean:
	rm -rf ${FSROOT}/usr/rtl8192su/
