var data_language = {
		innerHTML : {
			lang_status_help_menu : 'Ayuda de Estado',
			lang_devinfo : 'Información del dispositivo',
			lang_wiress_client : 'Clientes inalámbricos',
			lang_dhcp_client : 'Clientes DHCP',
			lang_logs : 'Registros',
			lang_statistics : 'Estadísticas',
			lang_routeinfo : 'Información de Ruta',
			lang_devinfo_subtitle : 'Información de Dispositivo',
			lang_devinfo_help : 	'<p>Esto muestra información detallada del enrutador, como por ejemplo la versión del firmware, cargador de arranque, y la dirección LAN IP.</p><dl><dt>Sistema Info<dd><dl><dt>Nombre del modelo<dd>Modelo del enrutador ADSL. <dt>Hora y Fecha <dd>Tiempo interno del enrutador. <dt>Versión de Firmware <dd>La versión actual del firmware.</dd></dl><BR><dt>Información de Internet<dd> Muestra las conexiones WAN configuradas en la sección <a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=setup&var:page=wancfg">Setup -> Internet Setup</a>. La columna "Estado" indica si el enlace ADSL está activo, y no necesita ser configurado.<dl><dt>Conexión de Internet <dd>Configuración de las conexiones a Internet creadas.<dt>Estado de la conexión a Internet <dd>Indica si la conexión seleccionada es hacia arriba o hacia abajo.<dt>Puerta de enlace predeterminada <dd>La Dirección IP actual de la puerta. Puede configurar manualmente la puerta de entrada o configurarla para "Auto" en <a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=advanced&var:page=route">Advanced -> Routing</a>.<dt>DNS preferido y alternativo <dd><p> Muestra los servidores DNS preferidos en la actualidad (Primario) y suplentes (secundario). Puede configurar manualmente la información del servidor DNS o configurarlo para "auto" en <a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=advanced&var:page=dns">Advanced -> DNS</a>.</p><dt>Tasa de Línea Ascendente (Kbps)<dd>Indica el tipo de carga en cuestión de segundos. Sólo está disponible cuando está conectado a su ISP.<dt>Tasa de Línea Descendente (Kbps)<dd>Indica la velocidad de descarga en cuestión de segundos. Sólo está disponible cuando está conectado a su ISP.</dd></dl><BR><dt>Información inalámbrica <dd>Esto muestra información detallada de las configuraciones de WLAN configuradas en <a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=setup&var:page=wireless&var:subpage=wlbasic">Setup -> Inalámbrico</a><dl><dt>Dirección Mac<dd>Su dirección MAC inalámbrica.<dt>Estado<dd>Indica si la red inalámbrica está habilitada.<dt>Nombre de la red (SSID):<dd>El nombre de red inalámbrica.<dt>visibilidad<dd>Indica si la red inalámbrica es visible para otros dispositivos inalámbricos.<br>En el modo visible, su nombre de red inalámbrica se difunde a todos los dispositivos dentro del rango de la señal. En el modo invisible, deberá introducir manualmente el nombre de red inalámbrica (SSID) en un dispositivo inalámbrico para conectarse a la red.<dt>Modo de seguridad <dd>Esto muestra las configuraciones de seguridad actuales.</dd></dl><BR><dt>Información de Red Local <dd>Esto muestra la configuración de LAN detallada del enrutador.<dl><dt>Dirección Mac<dd>La dirección MAC del enrutador.<dt>Dirección IP<dd>La dirección IP del enrutador.<dt>Máscara de Subred <dd>Máscara de subred del enrutador.<dt>Servidor DHCP<dd>Indica si DHCP está habilitado en el enrutador.</dd></dl>',
			lang_wireless_subtitle : 'Clientes inalámbricos',
			lang_wireless_help1 : '<p>Muestra las estaciones (identificadas por su BSSID) que se asocian con el enrutador inalámbrico. Haga clic en "Actualizar" para actualizar la página que muestra las nuevas estaciones inalámbricas.</p>',
			lang_dhcpclient : 'Clientes DHCP',
			lang_dhcpclient_help : '<p>Esto muestra los equipos que obtuvieron las direcciones IP del servidor DHCP, excepto el tiempo de arrendamiento en cuya dirección IP ha transcurrido, cada uno identificado por el nombre de la computadora prinicipal y la dirección MAC.</p>',
			lang_log_subtitle : 'Registros',
			lang_log_help : '<p>Si el registro está habilitado, el sistema comienza a registrar los niveles de determinados eventos, que pueden incluir emergencia, alerta, error crítico, advertencia, aviso, información y depuración. Los eventos que están por encima o igual que el nivel de visualización seleccionado se mostrarán.</p><p>El recorrido de navegación para configurar los registros del sistema es como sigue: <a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=maintenance&var:page=syslog">Maintenance -> System Log</a>.</p>',
			lang_statistics_subtitle : 'Estadisticass',
			lang_statistics_help : '<p>La página de "Estadística" muestra los datos de transmisión y recepción de los paquetes de red LAN, Red de Área extensa e inalámbrica.</p><dl><dt>Transmitido<dd>El número de paquetes enviados desde el enrutador.<dt>Recibido<dd>El número de paquetes recibidos por el enrutador.<dt>Paquetes Transmitidos Caídos <dd> El número de paquetes que se caen al mismo tiempo que se envían, debido a errores, colisiones, o limitaciones de recursos del enrutador.<dt>Paquetes recibidos Caídos <dd>El número de paquetes que se caen, mientras que se reciben, debido a errores, colisiones, o las limitaciones de recursos del enrutador.<dt>Errs<dd>El número de fallas de transmisión que causan la pérdida de un paquete. Un entorno ruidoso de radiofrecuencia puede causar una alta tasa de error en la LAN inalámbrica.<dt>Estadísticas ADSL <dd>Muestra las estadísticas de ADSL de datos, incluyendo el estado del enlace, las tasas descendentes y ascendentes, el tipo y la codificación de línea.</dd></dl>',
			lang_routeinfo_subtitle : 'Información de Ruta',
			lang_routeinfo_help : '<p>La página de Información de ruta muestra la información de enrutamiento, incluidas las direcciones IP de destino, puerta de enlace y máscara de subred.</p>'
		}

}