var data_language = {
	innerHTML : {
	'lang_management_help'      : 'Ayuda de Administración',
	'lang_firmware_update'	            : 'Actualización del Firmware',
	'lang_access_control'       : 'Controles de Acceso',
	'lang_dgn'					: 'Diagnosticos',
	'lang_log'					: 'Registro del Sistema',
	'lang_system_subtitle' : 'Sistema',
	'lang_system_help' : '<dl><dd>En esta página, usted puede administrar la configuración del enrutador, reiniciar el enrutador, hacer una copia de la configuración actual, cargar los ajustes previamente guardados, y restaurar el enrutador a los valores predeterminados de fábrica. Al Restaurar el enrutador a los valores predeterminados de fábrica se borrarán todos los ajustes actuales, incluyendo las reglas creadas. <dt>Reiniciar <dd>Esta función sirve para reiniciar el enrutador para que los cambios surtan efecto.<dt>Configuración de copia de seguridad	<dd>Usted puede utilizar esta función para guardar la configuración en un archivo en el ordenador para su uso posterior. Asegúrese de guardar la configuración antes de actualizar el firmware.	<dt>Configuración de la Actualización	<dd> Usted puede utilizar esta función para restaurar la configuración del enrutador previamente guardado.	<dt>Restaurar Configuración por Defecto	<dd>Esta función es para restaurar todos los ajustes a los parámetros configurados cuando el enrutador se envía a desde la fábrica. Todos los ajustes actuales se perderán. Si desea guardar la configuración actual, por favor haga clic en Configuración de copia de seguridad.</dd>	</dl>',
	'lang_upgrade_subtitle' : 'Actualización del Firmware',
	'lang_upgrade_help' : '<dl> <dd>En la página "Actualización de Firmware", usted puede actualizar el firmware del enrutador a lo último, para mejorar la funcionalidad y el rendimiento. <p> Para actualizar el firmware, haga lo siguiente: </p> <ol> <li>Haga clic en el Botón <span class=button_ref>Browse</span> para localizar el archivo de actualización en su equipo.	<li> Seleccione el archivo y haga clic en el Botón  <spanclass=button_ref>Update Firmware</span> para iniciar la actualización del firmware. Este proceso tarda aproximadamente un minuto. <li>Espere a que el enrutador se reinicie. El proceso de reinicio tarda aproximadamente un minuto. </ol> <dd> Nota: Algunas actualizaciones de firmware restablecen la configuración del enrutador a los valores predeterminados de fábrica. Antes de realizar una actualización, asegúrese de guardar la configuración actual. El recorrido de navegación es como sigue: <a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=maintenance&var:page=system">Maintenance -> System</a> screen. </dd> </dl>',
	'lang_access_subtitle' : 'Controles de acceso',
	'lang_access_help'   : 	'<dl>	<dt>Contraseña de la Cuenta	<dd><p> En esta página, usted puede establecer una contraseña para acceder a la interfaz de administración de Red. De forma predeterminada, no hay ninguna contraseña configurada. Se recomienda crear una contraseña para mantener su nuevo enrutador seguro.</p> <p>Puede acceder al enrutador DSL como una de las tres cuentas de usuario: administración, soporte, y usuario.</p> <dl> <dt>Contraseña de Administrador	<dd>Introduzca una contraseña para el usuario de "administración", que tiene acceso completo a la interfaz de administración de red. <dt>Contraseña de Soporte <dd>El usuario de "soporte" puede ser utilizado por un técnico de ISP para acceder al enrutador ADSL para mantenimiento y para ejecutar el diagnóstico. <dt>Contraseña de usuario	<dd> El usuario "usuario" puede ver la configuración y las estadísticas, así como actualizar el firmware del enrutador.	</dd></dl></dd></dl><dl><dt>Servicios<dd>Permite el acceso al enrutador a través de FTP, HTTP, ICMP, SNMP, SSH, TELNET, y TFTP.<dl><dt>LAN<dd> Accede al enrutador DSL de la red local (LAN).<dt>Red de Área Extensa<dd>Accede al enrutador DSL desde el lado del ISP.</dd></dl></dd></dl><dl>	<dt>Dirección IP <dd>Si esta opción está activada, sólo se especifican las direcciones IP pueden acceder al enrutador. Esta opción funciona con <b>Servicios</b>.</dd></dl>',
	'lang_dgn_subtitle' : 'Diagnosticos',
	'lang_dng_help' : '<p>Diagnósticos ejecuta pruebas de diagnóstico para comprobar la conexión DSL. Los resultados son acerca de las siguientes tres conexiones:</p><ul><li>Conexión a la red local <li>Conexión con el proveedor de servicios DSL <li>Conexión con el proveedor de servicios de Internet </ul>',
	'lang_log_subtitle' : 'Registro del Sistema',
	'lang_log_help' : '<p> Si el registro está habilitado, el sistema comienza a registrar todos los eventos seleccionados.</p><dl><dt>Nivel de registro <dd>HEl nivel de los registros que se guardan. <dt>Nivel de despliegue <dd>El nivel de los registros que se mostrará en la página de registro.<p>Si el modo está ajustado en "remoto", los registros se envían a la dirección IP y el puerto UDP de un servidor syslog remoto. Si el modo está establecido en "Local", los registros se reconocen en el equipo local. Si se establece "Ambos", los registros se guardan en el equipo local y el servidor syslog remoto. Seleccione los valores deseados y haga clic en "Aplicar" para guardar la configuración del registro del sistema.</p><dt>Ver registro del Sistema <dd>En esta página, puede ver los registros corresponde con el nivel que usted establece.</dd>'
	
	}
	
}