var data_language = {

	innerHTML : {
		lang_advance_help1 : 'Ayuda Avanzada',
		lang_AdvancedHelp : '<ul><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#AdvWlan">Advanced Wireless</a><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#PortForwarding">Port Forwarding</a></li><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#DMZ">DMZ</a></li><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#Parental"> Parental Control</a></li><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#Filtering"> Filtering Options</a></li><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#Firewall"> Firewall Settings</a></li><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#DNS">DNS</a></li><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#DDNS">DDNS</a></li><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#Tools"> Network Tools</a></li><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#Routing">Routing</a></li><li><a href="/cgi-bin/webproc?getpage=html/index.html&var:menu=help&var:page=helpadv#Schedules">Schedules</a></li></ul>',
		AdvWlan : 'Inalámbrico Avanzado',
		lang_div_blackhelp_table : '<p>La configuración inalámbrica Avanzada contiene las siguientes 3 partes:</p><ul clase="ayuda_tabla"><li> Configuraciones avanzadas <li>MAC Filtrado<li>Seguridad</ul><dl><dt>Configuraciones avanzadas<dd>Ajustes adicionales para configurar su red inalámbrica.<dl><dt> Velocidad de transmisión<dd>La tasa de conexión inalámbrica a la que se transmite la información y es recibida en su red inalámbrica.<dt>Velocidad de Multidifusión <dd>La velocidad a la que se envía un mensaje a un grupo específico de destinatarios.<dt>Potencia de transmisión<dd>El porcentaje de potencia que debe ser transmitido desde el enrutador inalámbrico. Se puede seleccionar un 20%, 40%, 60%, 80% o 100%.<dt>Período de Señal<dd>Un paquete de datos enviado desde un dispositivo conectado a todos los demás dispositivos, lo que indica su disponibilidad y disposición. Un intervalo de señal es un período de tiempo (enviado con la señal) antes de enviar la señal de nuevo. El intervalo de señal se puede ajustar en milisegundos (ms).<dt>Umbral RTS (Umbral de petición de envío)<dd>Esto determina el tamaño máximo del paquete que se puede transmitir en el enrutador, para ayudar al control de flujo del tráfico.<dt>Umbral de Fragmentación<dd>Esto ayuda a mejorar el rendimiento de transmisión de la red en la presencia de radio frecuencia (RF).<dt>Intervalo DTIM<dd>El intervalo de llamada de los clientes en el modo de ahorro de energía.<dt>TIPO Preámbulo<dd>La longitud de la comprobación del bloque de redundancia cíclica (CRC) para la comunicación entre el enrutador y los clientes inalámbricos. Para las zonas de alto tráfico de red, puede configurar el tipo de preámbulo a "corto".</dd></dl><br><dt>Filtro MAC<dd>Filtra los paquetes entrantes en el enrutador inalámbrico basado en su dirección MAC.<br><dt>Seguridad<dd> Ajustes para conseguir otros "clientes" de redes inalámbricas.</dd></dl>',
		PortForwarding : 'Renvío del puerto',
		lang_Multipleconnectionarer : 'Algunas aplicaciones, como juegos de Internet, videoconferencia, telefonía por Internet, requieren múltiples conexiones. Estas aplicaciones tienen dificultades para trabajar a través de la Traducción de Direcciones de Red (NAT). En esta página, usted puede abrir varios puertos (mediante la selección de varios puertos o especificar un rango de puertos) en el enrutador y redirigir los datos a través de esos puertos a un solo PC en su red.',
		DMZ : 'DMZ',
		lang_DMZ : '<dl><dt>Computadora Principal DMZ<dd><p>DMZ se refiere a la "zona desmilitarizada". Si una aplicación tiene problemas para trabajar detrás del enrutador, se puede exponer a un ordenador a Internet y ejecutar la aplicación en ese equipo </p><p>uando una LAN de host está configurada como un host DMZ, se convierte en el destino de todos los paquetes entrantes que no coinciden con algunas de las sesiones o reglas entrantes. Si hay alguna otra regla de entrada, esa regla se utiliza, y los paquetes no se envían a la computadora principal DMZ. Es decir, una sesión activa, un servidor virtual, un disparador de puerto activo, o una regla de renvío de puertos tiene mayor prioridad que la regla de enviar un paquete a la computadora principal DMZ. (La política DMZ se asemeja a un puerto por defecto de regla de renvío que renvía todos los puertos que no son específicamente enviados a ninguna otra parte.) </p><dd><p><B>Note:</B> El Ajuste de un ordenador a una computadora principal DMZ puede exponer la computadora a una variedad de riesgos de seguridad. Esta función sólo debe utilizarse como último recurso.</p> <dl><dt>Dirección IP DMZ<dd>Especifique la dirección IP de la LAN de la computadora de la cual usted desea tener una comunicación sin restricciones a Internet. Si este equipo obtiene su dirección de forma automática a través de DHCP, usted puede configurar la reserva de dirección IP estática en la página de Configuración de Red Básica. De esta manera, la dirección IP del ordenador DMZ no cambia.</dd></dl></dd></dl>',
		Parental : 'Control Parental',
		lang_Parentaldsc : '<dl><dt>control parental<dd>Usted puede utilizar esta función para bloquear ciertos sitios de red desde los que accede. Por ejemplo, si configura para negar "ww.blockthiswebsite.com", el acceso a este sitio será bloqueado de acuerdo con la programación establecida.<dt>Dirección MAC de Bloque<dd><p> En un escenario residencial, los padres pueden especificar la hora y el día de la semana cuando algunos equipos pueden acceder a Internet.</p> <div class=help_example><dl><dt>Example:<dd><p>Si desea que su hijo acceda a Internet desde las 7:00pm a las 9:00pm de Lunes a Viernes.</p><ol><li>puede establecer el nombre de usuario para "BeforeAccess ", e introduzca la dirección MAC del ordenador de su hijo.<li>A continuación, seleccione las casillas de verificación de lunes a viernes y la hora de inicio a las 00:00 y la hora de finalización a las 19:00.<li> De esta manera, el ordenador de su hijo no puede acceder a Internet desde las 12:00am a 7:00 pm, de lunes a viernes.<li> Repita los pasos anteriores, pero introduzca "AfterAccess" en el campo de nombre de usuario y la hora de inicio a las 21:00 y la hora de finalización a las 23:59.<li> La regla está completamente establecida. Como resultado, el equipo de su hijo puede acceder a Internet de 19:00-21:00 de lunes a viernes.</ol></dd></dl></div></dd></dl>',
		FilteringOptions : 'Opciones de Filtrado',
		lang_FilteringOptions : '<p>Puede configurar filtros para administrar el tráfico entrante y saliente. Haga clic en los Botones <span class=button_ref>Inbound</span>, <span class=button_ref>Outbound</span> y <span class=button_ref>Bridge</span> para proceder a una configuración adicional.</p><dl><dt>Inbound/Outbound Filtering<dd><p>Cuando se utiliza la activación de puertos o el reenvío de puertos para abrir los puertos para el tráfico desde Internet, el riesgo de que LAN sea atacado por hackers desde Internet aumenta. En este caso, puede utilizar filtros de entrada para controlar el riesgo mediante la especificación de direcciones IP de servidores de Internet que permiten acceder a la red LAN a través de los puertos que se abren. Por ejemplo, puede configurar la función de permitir el acceso a un servidor de juegos de la red LAN de sólo los ordenadores de amigos a los que invite a jugar en ese servidor.</p><p> La función de los filtros de entrada ayuda a controlar el acceso a un servidor en su red, de modo que sólo un sistema o grupo de sistemas puede acceder al servidor. Las reglas de filtrado pueden trabajar con la función de activación de puertos. Cada filtro se puede utilizar para varias funciones. Por ejemplo, un filtro "clan de juego" puede permitir a todos los miembros de un grupo de jugadores en particular jugar varios juegos diferentes para los cuales las entradas de juego han sido creadas. Mientras tanto, un filtro "administrador"  puede permitir sólo sistemas desde la red de su oficina para acceder a las páginas de la Red de Área Extensa para el usuario de "administración" y usted utiliza un servidor FTP en el hogar. Si agrega una dirección IP a un filtro, la dirección IP se ajusta a todas las reglas existentes del filtro.</p><p>La función de los filtros de salida ayuda a controlar el acceso a Internet a los ordenadores LAN. Los filtros pueden trabajar con la característica de renvío de puertos. El Filtro de salida también puede ser utilizado en conjunción con el filtro de entrada para permitir la entrada y restringir el acceso a la salida para el juego sobre la descarga de Internet o archivo.</p><dt> Puente de filtrado <dd>También es conocido como filtrado de direcciones MAC. Puede renviar o denegar el tráfico entrante en función de la fuente o la dirección MAC de destino. Tenga en cuenta que el puente de filtrado funciona con las interfaces que se configuran como puente.</dd></dl>',
		FirewallSettings : 'Configuración del Cortafuegos',
		lang_FirewallSettings : '<p id="lang_FirewallSettings">Esto ayuda a proteger su enrutador contra ataques de negación de servicio (DoS).</p>',
		DNS : 'DNS',
		lang_dns : '<p id="lang_dns">El Servidor de Nombre de Dominio (DNS) es un servidor que traduce un nombre URL/dominio para la dirección IP correspondiente. La Internet se basa en la dirección IP y el URL/nombre de dominio de orden alfabético es más fácil de recordar.</p>',
		DDNS : 'DDNS',
		lang_ddns : '<dl><dt>D-Proveedor de DNS <dd>Seleccione un proveedor de DNS dinámico desde la lista de servicio desplegable.<dt>Hostname<dd>Introduzca su nombre de computadora principal completo, por ejemplo myhost.mydomain.net</b><dt>Nombre de Usuario<dd> Introduzca el nombre de usuario proporcionado por su proveedor de servicios.<dt>Contraseña<dd>Introduzca la contraseña proporcionada por su proveedor de servicios.</dl>',
		NetworkTools : 'Herramientas de Red',
		lang_NetworkTools : '<dl><dt>Asignación de puerto <dd>La asignación de puerto soporta la asignación de un grupo de puertos que incluye uno o más (LAN) a un PVC, que se asocia con una VLAN. Como resultado, cada grupo de puertos LAN sirve como una red independiente (lógica) (como un dominio de difusión) en contra de la cual el tráfico de difusión nos ha prevenido. Esta función es útil para la creación de múltiples redes independientes (lógicas) para aplicaciones multimedia en el hogar. Por ejemplo, usted puede asignar PVC1 a los puertos 1-3 para crear una red (dominio de difusión) para que los PC accedan a Internet y un trazar PVC2 al puerto 4 para crear otra red (dominio de difusión) para el servicio de IPTV (dispositivos). Con esta característica (PVC múltiples), el tráfico de datos y el tráfico de IPTV no ??se afectan entre sí. <dt>IGMP<dd> IGMP soporta la multidifusión - transmisión eficiente de contenidos idénticos, tales como multimedia, desde un origen hacia un número de destinatarios.<dt>Configuración de Cola <dd>En esta página, usted puede disponer la configuración "Cola de Clasificación de Asignación " de QoS. Estos valores determinan la prioridad de QoS.<dt>QoS	<dd>QoS es una característica que ayuda a asignar o garantizar el rendimiento o la velocidad de la conexión a Internet de los ordenadores.<dt>UPnP<dd>Es sinónimo de Plug and Play universal, que es un conjunto de protocolos de red que proporciona la compatibilidad entre dispositivos de red, programas y periféricos. Este enrutador tiene una capacidad UPnP opcional, y puede trabajar con otros dispositivos UPnP y el programa.<dt>ADSL<dd> La "Configuración ADSL " de la página contiene la modulación y las opciones de capacidad. Consulte su ISP para obtener los ajustes correctos. A continuación, haga clic en "Aplicar" para finalizar la configuración o haga clic en "Configuración avanzada" para disponer la configuración más avanzada.<dt>SNMP<dd>El Protocolo de Administración de Red Simple (SNMP) proporciona un medio para supervisar el estado y rendimiento, así como establecer los parámetros de configuración. Permite a una estación de administración configurar, monitorear y recibir mensajes de captura desde dispositivos de red.<dt>TR-069<dd>TR-069 es un protocolo de gestión de Red de Área Extensa. Como un SOAP/HTTP bidireccional  basado en el protocolo, permite la comunicación entre el enrutador ADSL y un servidor de configuración automática (ACS).</dd></dl>',
		Routing : ' Enrutamiento',
		lang_Routing : 'La Ruta estática, la puerta de enlace predeterminada, y las configuraciones de tipo RIP de enrutamiento se pueden realizar aquí.',
		Schedules : 'Programaciones',
		lang_Schedules : '<p>Los horarios pueden ser creados para hacer cumplir las reglas. Por ejemplo, si desea restringir el acceso a la red de lunes a viernes de 3 pm a 8 pm, puede crear un programa, la selección de lunes, martes, miércoles, jueves y viernes, y el establecimiento de la hora de inicio 3 pm y la hora de finalización de 8pm.</p><dl><dt> Regla de Programación Añadir/Editar <dd>En esta página, usted puede añadir una entrada en la lista de Reglas  de Programación o editar una entrada existente.<dl><dt>name<dd>Establezca el nombre del programa, por ejemplo, "regla de día de la semana".<dt>Día(s)<dd>Seleccione las casillas de verificación que corresponden a los días que desee o seleccione la opción del botón de radio "Toda la semana" para seleccionar toda la semana.<dt>Todo el día - 24 hrs<dd> Seleccione esta opción si desea que la programación tenga efecto durante todo el día del día(s) seleccionado.<dt>Tiempo de Inicio<dd>Si usted no selecciona la opción "Todo el Día", por favor, especificar el tiempo aquí. Ajuste la hora y los minutos en los dos campos de la hora de inicio. Normalmente, los eventos de correo electrónico se activan sólo por el tiempo de inicio.<dt>Tiempo de Finalización<dd> El tiempo de finalización tiene el mismo formato que la hora de inicio. La hora de finalización se aplica a la mayoría de las demás normas así como en los eventos de correo electrónico.<dt>aplicar<dd> Después de terminar establezca una norma de programación nueva o modificación o una ya existente, haga clic en el botón <span class=button_ref>Apply</span> para guardar los ajustes o cambios.</dd></dl><dt>Lista de Reglas de programación <dd>Muestra las reglas de programación definidas. Puede hacer clic en <span class=button_ref>Edit</span> para modificar una regla de programación, o haga clic en el botón <span class=button_ref>Delete</span>para eliminar una regla programación.</dd></dl>'
	}
	
}  
