#
# linux/drivers/devices/Makefile
#

obj-$(CONFIG_MTD_DOC2000)	+= doc2000.lib
obj-$(CONFIG_MTD_DOC2001)	+= doc2001.lib
obj-$(CONFIG_MTD_DOC2001PLUS)	+= doc2001plus.lib
obj-$(CONFIG_MTD_DOCPROBE)	+= docprobe.lib
obj-$(CONFIG_MTD_DOCECC)	+= docecc.lib
obj-$(CONFIG_MTD_SLRAM)		+= slram.lib
obj-$(CONFIG_MTD_PHRAM)		+= phram.lib
obj-$(CONFIG_MTD_PMC551)	+= pmc551.lib
obj-$(CONFIG_MTD_MS02NV)	+= ms02-nv.lib
obj-$(CONFIG_MTD_MTDRAM)	+= mtdram.lib
obj-$(CONFIG_MTD_LART)		+= lart.lib
obj-$(CONFIG_MTD_BLOCK2MTD)	+= block2mtd.lib
obj-$(CONFIG_MTD_DATAFLASH)	+= mtd_dataflash.lib
obj-$(CONFIG_MTD_M25P80)	+= m25p80.lib
